/** FenMeat Sales V2 reporting sync. Install only in the separate test spreadsheet. */
const SALES_V2_URL = 'https://fenmeat-sales-test.alexander-fenwick.workers.dev';
const SALES_V2_SHEET_TITLE = 'FenMeat Sales V2 — Test';
const SALES_V2_FIRST_DATE = '2026-09-30';

function onOpen() {
  SpreadsheetApp.getUi().createMenu('Sales V2').addItem('Connect reports', 'setupSalesV2Sync').addItem('Refresh reports', 'syncSalesV2Reports').addItem('Rebuild full report history', 'rebuildSalesV2Reports').addItem('Stop automatic refresh', 'stopSalesV2Sync').addToUi();
}
function salesV2Sheet_() {
  const id = PropertiesService.getScriptProperties().getProperty('SALES_V2_SHEET_ID');
  if (!id) throw new Error('Run setupSalesV2Sync in the separate Sales V2 test spreadsheet first.');
  const ss = SpreadsheetApp.openById(id);
  if (ss.getName() !== SALES_V2_SHEET_TITLE) throw new Error('The target is not the Sales V2 test spreadsheet.');
  return ss;
}
function setupSalesV2Sync() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  if (!ss || ss.getName() !== SALES_V2_SHEET_TITLE || !['Overview','Route_Items','Cash_Up','History','Data_Review'].every(name => ss.getSheetByName(name))) throw new Error('Open the supplied Sales V2 test spreadsheet before setup.');
  const ui = SpreadsheetApp.getUi();
  const reply = ui.prompt('Connect Sales V2 reports', 'Paste your personal Sales V2 access key. It is saved in Script Properties, never in a cell. People with edit access to this script can access it.', ui.ButtonSet.OK_CANCEL);
  if (reply.getSelectedButton() !== ui.Button.OK) return;
  const key = reply.getResponseText().trim();
  if (!/^[a-f0-9]{64}$/.test(key)) throw new Error('Use the 64-character key generated by the test app.');
  PropertiesService.getScriptProperties().setProperties({SALES_V2_ACCESS_KEY: key, SALES_V2_SHEET_ID: ss.getId()});
  syncSalesV2Reports();
  stopSalesV2Sync();
  ScriptApp.newTrigger('syncSalesV2Reports').timeBased().everyMinutes(10).create();
  ui.alert('Reports connected. They will refresh every 10 minutes.');
}
function stopSalesV2Sync() {
  ScriptApp.getProjectTriggers().forEach(t => { if (t.getHandlerFunction() === 'syncSalesV2Reports') ScriptApp.deleteTrigger(t); });
}
function salesV2Request_(path, body) {
  const key = PropertiesService.getScriptProperties().getProperty('SALES_V2_ACCESS_KEY');
  if (!key) throw new Error('Run setupSalesV2Sync first.');
  const options = {method: body ? 'post' : 'get', headers: {Authorization: 'Bearer ' + key}, muteHttpExceptions: true};
  if (body) { options.contentType = 'application/json'; options.payload = JSON.stringify(body); }
  const response = UrlFetchApp.fetch(SALES_V2_URL + path, options);
  if (response.getResponseCode() !== 200) throw new Error('Sales V2 returned HTTP ' + response.getResponseCode() + '. Check the access key and app status.');
  return JSON.parse(response.getContentText());
}
function salesV2Date_(date) { return Utilities.formatDate(date, 'Africa/Johannesburg', 'yyyy-MM-dd'); }
function salesV2Add_(date, days) { return new Date(Date.parse(date + 'T12:00:00Z') + days * 86400000).toISOString().slice(0, 10); }
function syncSalesV2Reports() { salesV2Sync_(false); }
function rebuildSalesV2Reports() { salesV2Sync_(true); }
function salesV2Sync_(fullHistory) {
  const lock = LockService.getScriptLock();
  if (!lock.tryLock(1000)) return;
  let overview;
  try {
    const ss = salesV2Sheet_(); overview = ss.getSheetByName('Overview');
    if (!overview || !ss.getSheetByName('Route_Items') || !ss.getSheetByName('Cash_Up')) throw new Error('The reporting tabs are missing.');
    const today = salesV2Date_(new Date());
    let from = fullHistory ? SALES_V2_FIRST_DATE : salesV2Add_(today, -90);
    const runs = [];
    while (from <= today) {
      const to = [salesV2Add_(from, 90), today].sort()[0];
      const result = salesV2Request_('/api/sync/export?from=' + from + '&to=' + to);
      if (!Array.isArray(result.runs)) throw new Error('Unexpected report response.');
      runs.push.apply(runs, result.runs);
      from = salesV2Add_(to, 1);
    }
    const items = [], cash = [];
    const rand = value => value == null ? '' : value / 100;
    for (const e of runs) {
      const r = e.run, s = e.summary;
      for (const i of s.items) items.push([r.date, r.route, i.code, i.name, i.planned, i.loaded, i.returned, i.adjustment, i.sold, i.invoiced, i.variance, r.phase, e.revision, e.actor, e.saved_at, i.adjustment_reason]);
      cash.push([r.date, r.route, r.rep, rand(r.cash.counted), rand(s.expected), rand(s.cashVariance), r.recon ? rand(s.currentCash) : '', r.recon ? rand(s.oldCash) : '', r.recon ? rand(s.unallocatedCash) : '', rand(r.cash.float), rand(r.cash.banked), rand(r.cash.expenses), rand(r.cash.extra), rand(s.variances.shop2shop), rand(s.variances.card), rand(s.variances.eft), r.phase, e.revision, e.saved_at]);
    }
    salesV2Merge_(ss.getSheetByName('Route_Items'), items, 16, 3);
    salesV2Merge_(ss.getSheetByName('Cash_Up'), cash, 19, 2);
    SpreadsheetApp.flush();
    salesV2Request_('/api/sync/ack', {spreadsheet_id: ss.getId()});
    overview.getRange('B5:B7').setValues([['Connected — reports refreshed'], [new Date()], ['']]);
    overview.getRange('B6').setNumberFormat('yyyy-mm-dd hh:mm:ss');
  } catch (error) {
    if (overview) { overview.getRange('B5').setValue('Sync failed — reports may be stale'); overview.getRange('B7').setValue(salesV2Date_(new Date()) + ': ' + String(error.message).slice(0, 300)); }
    throw error;
  } finally { lock.releaseLock(); }
}
function salesV2Merge_(sheet, incoming, columns, keyColumns) {
  const count = Math.max(0, sheet.getLastRow() - 4);
  const old = count ? sheet.getRange(5, 1, count, columns).getValues() : [];
  const map = new Map();
  const normalized = row => { if (row[0] instanceof Date) row[0] = salesV2Date_(row[0]); return row; };
  const key = row => row.slice(0, keyColumns).join('|');
  for (const row of old) if (row[0]) { normalized(row); map.set(key(row), row); }
  for (const row of incoming) map.set(key(row), row);
  const rows = Array.from(map.values()).sort((a, b) => key(a).localeCompare(key(b))).map(row => row.map(v => v == null ? '' : typeof v === 'string' && /^[=+@-]/.test(v) ? "'" + v : v));
  if (rows.length) {
    if (sheet.getMaxRows() < rows.length + 4) sheet.insertRowsAfter(sheet.getMaxRows(), rows.length + 4 - sheet.getMaxRows());
    sheet.getRange(5, 1, rows.length, 1).setNumberFormat('@');
    sheet.getRange(5, 1, rows.length, columns).setValues(rows);
    sheet.getRange(5, sheet.getName() === 'Cash_Up' ? 4 : 5, rows.length, sheet.getName() === 'Cash_Up' ? 13 : 7).setNumberFormat(sheet.getName() === 'Cash_Up' ? '#,##0.00' : 'General');
  }
  if (count > rows.length) sheet.getRange(rows.length + 5, 1, count - rows.length, columns).clearContent();
}
