import test from 'node:test';import assert from 'node:assert/strict';
import {aggregateProductionDemand,buildProductionPlan,productionProfile,productionSummary,applyProductionSuggestion,validateProductionEdits,nextProductionTarget} from '../src/production.js';
const product=(code='W01')=>({code,name:code,unit:'bag',active:true,available:true});
function make(codes=['W01']){return buildProductionPlan({date:'2026-10-07',target_date:'2026-10-08',routes:['MB','PL'],snapshot:'test',items:codes.map(code=>({...product(code),...productionProfile(product(code)),demand:30,breakdown:[]}))});}
test('Braaiwors: total need 30, post-dispatch stock 10, two complete recipes and six bags left',()=>{const p=make();p.items[0].stock=10;const s=productionSummary(p).groups[0];assert.equal(s.suggested,2);assert.equal(p.groups[0].planned,null);applyProductionSuggestion(p,'W01');const planned=productionSummary(p).groups[0];assert.equal(planned.output,26);assert.equal(planned.balances[0].balance,6);p.groups[0].planned=1;assert.equal(productionSummary(p).groups[0].balances[0].balance,-7);assert.ok(productionSummary(p).groups[0].warnings.includes('My plan leaves a shortage'));});
test('enough stock gives zero, blank stock stays unknown, zero plan is kept',()=>{const p=make();assert.equal(productionSummary(p).groups[0].suggested,null);assert.equal(applyProductionSuggestion(p,'W01'),false);p.items[0].stock=30;assert.equal(productionSummary(p).groups[0].suggested,0);p.groups[0].planned=0;p.items[0].stock=0;assert.equal(applyProductionSuggestion(p,'W01',{blankOnly:true}),false);assert.equal(p.groups[0].planned,0);});
test('route quantities use manual override including zero; incomplete forecast remains unknown',()=>{const ps=[product()];const source=(route,planned,forecast)=>({route,name:route,revision:1,run:{items:[{code:'W01',planned}]},forecasts:{W01:{qty:forecast}}});assert.equal(aggregateProductionDemand(ps,[source('A',0,25),source('B',30,90)])[0].demand,30);assert.equal(aggregateProductionDemand(ps,[source('A',null,12),source('B',null,null)])[0].demand,null);});
test('shared Russian sizes round once and packing cannot exceed batch capacity silently',()=>{const p=make(['R01','R02']);p.items[0].demand=10;p.items[1].demand=10;for(const i of p.items)i.stock=0;assert.equal(productionSummary(p).groups[0].suggested,1);applyProductionSuggestion(p,'RUSSIAN');assert.equal(p.groups[0].planned,1);assert.deepEqual(p.items.map(i=>i.pack_plan),[10,10]);p.items[0].pack_plan=30;assert.ok(productionSummary(p).groups[0].warnings.includes('Packing plan exceeds planned batches'));});
test('polony sizes share recipe capacity; bought-in units never become cooking batches',()=>{const p=make(['P02','P03','B01']);for(const i of p.items)i.stock=0;p.items[0].demand=61;p.items[1].demand=30.5;const s=productionSummary(p);assert.equal(s.groups.find(g=>g.id==='POLONY').suggested,1);assert.equal(s.groups.find(g=>g.id==='B01').suggested,30);assert.equal(s.groups.find(g=>g.id==='B01').mode,'buy');});
test('refresh retains manual plan, stock, yield, actual output and product history',()=>{const p=make();Object.assign(p.items[0],{stock:10,yield_qty:14,actual:29});p.groups[0].planned=0;p.notes='Keep me';const next=buildProductionPlan({date:p.date,target_date:p.target_date,routes:p.routes,items:[{...p.items[0],demand:100}],snapshot:'changed',previous:p});assert.equal(next.items[0].stock,10);assert.equal(next.items[0].yield_qty,14);assert.equal(next.items[0].actual,29);assert.equal(next.groups[0].planned,0);assert.equal(next.notes,'Keep me');});
test('manual batches are whole; unsupported yields do not create a made-up suggestion',()=>{const p=make(['X01']);p.items[0].stock=0;assert.equal(productionSummary(p).groups[0].suggested,null);const v=structuredClone(p);v.groups[0].planned=.5;assert.throws(()=>validateProductionEdits(v,p));v.groups[0].planned=0;v.items[0].stock=-1;assert.throws(()=>validateProductionEdits(v,p));v.items[0].stock=0;v.items[0].yield_qty=0;assert.throws(()=>validateProductionEdits(v,p));});
test('next production target skips days with no scheduled routes',()=>{assert.equal(nextProductionTarget('2026-10-09',[{weekday:1}]),'2026-10-12');});
