import test from 'node:test';import assert from 'node:assert/strict';import {fileURLToPath} from 'node:url';import {Miniflare,convertV4MiniflareOptions} from 'miniflare';
const origin='https://production-local.example',key='test-production-key-012345678901234567890';
async function fixture(t){const mf=new Miniflare(convertV4MiniflareOptions({name:'production-test',modules:['worker','production-api','production','domain','forecast','month-cycle','forecast-history','auth','schema','zoho','zoho-matching'].map(n=>({type:'ESModule',path:fileURLToPath(new URL('../src/'+n+'.js',import.meta.url))})),compatibilityDate:'2026-09-30',d1Databases:{DB:'production-test'},bindings:{APP_ENV:'test',APP_ACCESS_KEYS:JSON.stringify({alex:key})},outboundService:()=>{throw Error('No outbound traffic in production tests');}}));t.after(()=>mf.dispose());let cookie='';async function call(path,body,headers={}){const r=await mf.dispatchFetch(origin+path,{method:body?'POST':'GET',headers:{Origin:origin,'Content-Type':'application/json',Cookie:cookie,...headers},body:body?JSON.stringify(body):undefined});return {status:r.status,data:await r.json(),headers:r.headers};}
 assert.equal((await call('/api/production?date=2026-10-07')).status,401);const auth=await call('/api/login',{username:'alex',key});cookie=auth.headers.get('set-cookie').split(';')[0];
 const catalog={products:[{code:'W01',name:'Braaiwors',unit:'bag',price_cents:16000,active:true,available:true}],routes:[{code:'MB',name:'Mossel Bay',weekday:4},{code:'PL',name:'Plett',weekday:4}]};assert.equal((await call('/api/catalog',{revision:0,catalog})).status,200);
 for(const route of ['MB','PL']){let r=(await call('/api/run?date=2026-10-08&route='+route)).data;r.run.items[0].planned=15;assert.equal((await call('/api/run',{run:r.run,revision:0,action:'save',request_id:crypto.randomUUID()})).status,200);}
 const save=(r,action='save',extra={})=>call('/api/production',{plan:r.plan,revision:r.revision,action,request_id:crypto.randomUUID(),...extra});return {mf,call,save};}
test('real D1 production save, reopen, refresh, explicit zero, stale/concurrent/idempotent writes and route isolation',async t=>{const {mf,call,save}=await fixture(t),db=await mf.getD1Database('DB');const before=(await db.prepare('SELECT * FROM v2_events ORDER BY run_id,revision').all()).results;
 let r=(await call('/api/production?date=2026-10-07')).data;assert.equal(r.plan.items[0].demand,30);r.plan.items[0].stock=10;r.plan.groups[0].planned=2;const body={plan:r.plan,revision:0,action:'save',request_id:crypto.randomUUID()};let first=await call('/api/production',body);assert.equal(first.status,200,JSON.stringify(first));r=first.data;assert.equal(r.summary.groups[0].output,26);assert.equal(r.summary.groups[0].balances[0].balance,6);
 assert.equal((await call('/api/production',body)).data.replayed,true);assert.equal((await call('/api/production',{...body,request_id:crypto.randomUUID()})).status,409);assert.equal((await call('/api/production',{...body,action:'refresh'})).status,409);
 assert.deepEqual((await call('/api/production?date=2026-10-07')).data.plan,r.plan);
 r.plan.groups[0].planned=0;r.plan.notes='Manual zero retained';r.plan.items[0].yield_qty=14;r=(await save(r)).data;
 let route=(await call('/api/run?date=2026-10-08&route=MB')).data;route.run.items[0].planned=25;await call('/api/run',{run:route.run,revision:route.revision,action:'save',request_id:crypto.randomUUID()});
 assert.equal((await call('/api/production?date=2026-10-07')).data.stale,true);r=(await save(r,'refresh')).data;assert.equal(r.plan.items[0].demand,40);assert.equal(r.plan.groups[0].planned,0);assert.equal(r.plan.items[0].stock,10);assert.equal(r.plan.items[0].yield_qty,14);assert.equal(r.plan.notes,'Manual zero retained');
 assert.equal((await save(r,'confirm')).status,400);r=(await save(r,'confirm',{acknowledge_warnings:true})).data;assert.equal(r.plan.phase,'confirmed');r.plan.items[0].actual=0;r=(await save(r,'actuals')).data;assert.equal(r.plan.phase,'confirmed');assert.equal(r.plan.items[0].actual,0);
 const tampered=structuredClone(r);tampered.plan.items[0].stock=100;assert.equal((await save(tampered,'actuals')).status,400);
 const events=(await db.prepare('SELECT * FROM v2_events ORDER BY run_id,revision').all()).results;assert.equal(events.length,before.length+1);assert.deepEqual(events.filter(e=>e.revision===1),before);assert.equal((await db.prepare('SELECT COUNT(*) n FROM v2_history').first()).n,0);
 assert.equal((await call('/api/production/audit?date=2026-10-07',{plan:r.plan,revision:r.revision,action:'save',request_id:crypto.randomUUID()})).status,405);
 assert.equal((await call('/api/production/audit?date=2026-10-07')).data.events.length,5);
 const wrongOrigin=await call('/api/production',{plan:r.plan,revision:r.revision,action:'save',request_id:crypto.randomUUID()},{Origin:'https://evil.example'});assert.equal(wrongOrigin.status,403);
 const next=(await call('/api/production?date=2026-10-08')).data;assert.equal(next.plan.items[0].stock,null);assert.equal(next.plan.items[0].yield_qty,14);assert.equal(next.plan.groups[0].planned,null);
});
test('production D1 rejects partial batches, missing plan decisions and tampered source quantities',async t=>{const {call,save}=await fixture(t);let r=(await call('/api/production?date=2026-10-07')).data;assert.equal((await save(r,'confirm',{acknowledge_warnings:true})).status,400);r.plan.groups[0].planned=.5;assert.equal((await save(r)).status,400);r.plan.groups[0].planned=2;r.plan.items[0].stock=10;r.plan.items[0].demand=99999;r=(await save(r)).data;assert.equal(r.plan.items[0].demand,30);r.plan.items[0].demand=1;r=(await save(r)).data;assert.equal(r.plan.items[0].demand,30);});
